symstore.exe add /o /r /f %CD%\Game\Runtime\Raiderz.pdb /s \\icecream\SYMBOLS\PRODUCTSYMBOLS /t "Raiderz" /compress > !svn_CopySynbol.log
symstore.exe add /o /r /f %CD%\Game\Runtime\Game.pdb /s \\icecream\SYMBOLS\PRODUCTSYMBOLS /t "Raiderz" /compress > !svn_CopySynbol.log
symstore.exe add /o /r /f %CD%\Game\Runtime\Dev\GameServer\GameServer_r.pdb /s \\icecream\SYMBOLS\PRODUCTSYMBOLS /t "Raiderz" /compress > !svn_CopySynbol.log
symstore.exe add /o /r /f %CD%\Game\Runtime\Dev\MasterServer\MasterServer_r.pdb /s \\icecream\SYMBOLS\PRODUCTSYMBOLS /t "Raiderz" /compress > !svn_CopySynbol.log
symstore.exe add /o /r /f %CD%\Game\Runtime\Dev\LoginServer\LoginServer_r.pdb /s \\icecream\SYMBOLS\PRODUCTSYMBOLS /t "Raiderz" /compress > !svn_CopySynbol.log
symstore.exe add /o /r /f %CD%\Game\Runtime\Dev\AppServer\AppServer_r.pdb /s \\icecream\SYMBOLS\PRODUCTSYMBOLS /t "Raiderz" /compress > !svn_CopySynbol.log
symstore.exe add /o /r /f %CD%\Game\Runtime\Dev\GameServer\GameServerConsole_r.pdb /s \\icecream\SYMBOLS\PRODUCTSYMBOLS /t "Raiderz" /compress > !svn_CopySynbol.log
symstore.exe add /o /r /f %CD%\Game\Runtime\Dev\MasterServer\MasterServerConsole_r.pdb /s \\icecream\SYMBOLS\PRODUCTSYMBOLS /t "Raiderz" /compress > !svn_CopySynbol.log
symstore.exe add /o /r /f %CD%\Game\Runtime\Dev\LoginServer\LoginServerConsole_r.pdb /s \\icecream\SYMBOLS\PRODUCTSYMBOLS /t "Raiderz" /compress > !svn_CopySynbol.log
symstore.exe add /o /r /f %CD%\Game\Runtime\Dev\AppServer\AppServerConsole_r.pdb /s \\icecream\SYMBOLS\PRODUCTSYMBOLS /t "Raiderz" /compress > !svn_CopySynbol.log
symstore.exe add /o /r /f %CD%\Game\Runtime\Dev\AppServer\AppServerConsole_r.pdb /s \\icecream\SYMBOLS\PRODUCTSYMBOLS /t "Raiderz" /compress > !svn_CopySynbol.log
symstore.exe add /o /r /f %CD%\Game\Runtime\DummyClient_r.pdb /s \\icecream\SYMBOLS\PRODUCTSYMBOLS /t "Raiderz" /compress > !svn_CopySynbol.log
symstore.exe add /o /r /f %CD%\Game\Runtime\Raiderz_DummyClient.pdb /s \\icecream\SYMBOLS\PRODUCTSYMBOLS /t "Raiderz" /compress > !svn_CopySynbol.log